### PR TITLE
Updated connectable.ts to 1.20.60 and added stuff

### PR DESCRIPTION
**Pull request by Miniontoby**
Updated connectable.ts to 1.20.60 and added stuff

Stuff added/changed/fixed:
- Added `direction_combinations` for making OR's possible between multiple collections of AND directions
- Added UP and DOWN variants of the North, East, South, West directions.
- Made the schema better with require statements
- Fixed the typescript issues

### CODE REVIEW

**Comment by Miniontoby** [comment]
I have made sure it works, since I am working on a block that requires connections.

Here is the prove that it works.

image

**Comment by Miniontoby** [comment]
> Make sure to request a review from me once it's ready 👍

I cannot find the button to request a review from you, but it is ready to be reviewed, tho

**Comment by outercloudstudio** [comment]
> > Make sure to request a review from me once it's ready 👍
> 
> I cannot find the button to request a review from you, but it is ready to be reviewed, tho

Ah might be a permissions things. I'll review it asap.

**Review by outercloudstudio — APPROVED** [review]
Looks good to me.

**Pull request merged**
