### PR TITLE
SimplyJson 1.1.0

### PR DESCRIPTION
**Pull request by Gekocaretaker**

### CODE REVIEW

**Review by Joelant05 — CHANGES_REQUESTED** [review]
Just a couple of things that need changing:

There is a slight spelling mistake in the `path` to the zip

The version number needs to be put to 1.2.0 because it has been updated already to fix another mistake before

**Comment by Joelant05** [comment]
Also could you resolve the conflicts by merging bridge-core/plugins into Gekocaretaker/plugins so you have the same files that are already on the repo on your fork

**Comment by Gekocaretaker** [comment]
I think I fixed it. I remade the zip file as well, but since I don't know how zip files work, it may not have worked

**Comment by Joelant05** [comment]
Moved to PR #8

**Pull request closed without merging**
