### PR TITLE
Vanilla Files Extension.

### PR DESCRIPTION
**Pull request by ihategravel2**
Adds client and regular entities to the file creation menu. 

I think this might be the biggest extension ever!

### CODE REVIEW

**Comment by ihategravel2** [comment]
Accidentally closed it :)

**Review by solvedDev — COMMENTED** [review]
It looks like you're using a mixture of v2.2 presets and v2.1 presets. If you want to support v2.2 later on, you would have to remove the direct pack path references like "BP/" or "RP/". Since it seems like you've already added the pack path property to your manifests, the presets should continue working as expected afterwards

**Comment by ihategravel2** [comment]
Ok thanks, I'll fix that

**Review by Joelant05 — APPROVED** [review]
As solved said, this will need updating when 2.2 comes out but this looks good to merge now, thanks!

**Comment by ihategravel2** [comment]
Got a version already ready when 2.2 comes out!

**Pull request merged**
