### PR TITLE
Added Simply Json

### PR DESCRIPTION
**Pull request by Gekocaretaker**
Simply Json adds new components that only work in bridge. and also auto completions for your own custom components.
Thank you to all the developers for helping me make the interact builder component.
So far there is upcraft:interaction_builder for the components, and $general.ores + $upcraft.startup for auto completions.

### CODE REVIEW

**Comment by 7dev7urandom** [comment]
You may want to remove some of the ores: copper, tin, steel, platinum and silver.

**Comment by solvedDev** [comment]
Make sure to make sure you only include the files you want to ship to users and then we should be good to go 👍

**Comment by Gekocaretaker** [comment]
I added those ores so people can use them themselves because those are very popular ores in addons.

**Review by solvedDev — APPROVED** [review]
I see 👌

**Pull request merged**
